# Generated by Django 6.0.4 on 2026-05-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_muscular', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriagrupomuscular',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='categoriagrupomuscular',
            old_name='name',
            new_name='nome',
        ),
    ]
