# Generated by Django 6.0.4 on 2026-05-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de alimento',
                'verbose_name_plural': 'Categorias de alimentos',
                'ordering': ['id'],
            },
        ),
    ]
