# Generated by Django 6.0.4 on 2026-06-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoesfisicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaofisica',
            options={'ordering': ['id'], 'verbose_name': 'Avaliação Física', 'verbose_name_plural': 'Avaliações Físicas'},
        ),
    ]
