# Generated by Django 6.0.4 on 2026-06-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinadores', '0003_alter_treinador_registrocref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='registroCREF',
            field=models.CharField(max_length=100, verbose_name='Registro CREF'),
        ),
    ]
