# Generated by Django 6.0.4 on 2026-06-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricionista',
            name='registroCRN',
            field=models.CharField(max_length=100, verbose_name='Registro CRN'),
        ),
    ]
